### ISSUE TITLE
Plugin broken after Upgrade to CMK 2.2

### ISSUE THREAD

**Issue by righter83** [kuhn-ruess/Checkmk-Checks#63]
Hi

I have update my CheckMK from 2.1 to 2.2p7 and also update the Pure Plugin from 1.3.1 to 1.4.2.
Afterwards I got this error:
`[special_pure] ModuleNotFoundError: No module named 'purity_fb'`

The pip package is still installed:
`purestorage          1.19.0`

any idea what is wrong here?

**Comment by Bastian-Kuhn** [comment]
Can you try pip(3) install purity_fb?

**Comment by righter83** [comment]
Hi

If I do that it will also update urlib3 from 1.26.13 to 2.0.4 which breaks other checks on CheckMK

But it was working if I update with no depdendencies!:
`pip3 install --no-deps purity_fb`

Thanks!

**Comment by Bastian-Kuhn** [comment]
Thanks for your Update, the new Version should not need this requirement at all anymore.

My only Problem I always have, can't test since I have no pure device.

**Comment by zbukhari-apex** [comment]
Well that solves one of my problems righter83, I manually installed purestorage because `pip3 intall purestorage` added in dependencies which "broke" checkmk. Perhaps the `readme.md` can be updated but not sure how many look at that. I think a larger point could be made for the folks at checkmk that allow one to put in a readme there or a pre/post install script ... which may be overkill. Not sure, tough stuff to plan, glad you're all helping out 🤷‍♂️ 

BTW the only issue I ran into after the `purestorage` python module was during pre-compile, it failed. I will create another issue for that.

**Comment by Bastian-Kuhn** [comment]
Can you please clarify that pip3 install --no-deps purestorage is sufficed with checkmk to have it work?
It's seams that the installation does not break any checkmk version, since that was the first report of it and I'm 100 % that I know installations which just did pip3 install purestorage.
